# Useful resources:
# http://www.stavros.io/posts/example-provisioning-and-deployment-ansible/
# https://github.com/azavea/ansible-gdal-netcdf
# https://github.com/snowplow/ansible-playbooks (see python-data-science.yml)
---
- hosts: all
  vars:
    sources_dir: /usr/local/src
    initfiles:
      - gunicorn

    - name: Download Miniconda
      sudo: yes
      get_url:
        url: http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
        dest: {{ sources_dir }}/miniconda.sh
        mode: 755

    - name: Install Miniconda
      sudo: yes
      shell: '{{ sources_dir }}/miniconda.sh -b'
